### PR TITLE
Fix small typo in totalPages

### PR DESCRIPTION
**Pull request by baldrailers**

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks, this will be a breaking change :(.

**Comment by NetanelBasal** [comment]
Can you keep the old key so we not break the code?

**Comment by baldrailers** [comment]
@NetanelBasal I just added `pages` so it'll be more clear.

**Comment by NetanelBasal** [comment]
It's hard to guess from this name that this is a number, you get what I mean?

**Comment by baldrailers** [comment]
I guess just keeping both `totaPages` and `totalPages` will cut it then. At some point.

**Pull request merged**
